name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v3

      - name: SSH orqali serverga yuklash va ishga tushirish
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/projects/CI-CD  # Loyihang joylashgan katalogga o‘t
            git pull origin main  # Kodni GitHub'dan yangilash
            pip install -r requirements.txt  # Python kutubxonalarni o‘rnatish
            systemctl restart ci-test  # Xizmatni qayta ishga tushirish
